### ISSUE TITLE
TAP Session Activity Crashes when TransactionMode.PURCHASE is selected.

### ISSUE THREAD

**Issue by umar2121** [Tap-Payments/goSellSDK-Android#10]
As the title says it all, the application crashes when I select TransactionMode.PURCHASE  in the function of SDKSession.
Following is the log of crash:
![image](https://user-images.githubusercontent.com/12980354/56111255-be962e80-5f70-11e9-8acb-8f678d15c0ce.png)

**Comment by matir91** [comment]
I debugged a bit the issue and it seems to be related to the [`permissions` list in the `data` field in the `SDKSettings` class](https://github.com/Tap-Payments/goSellSDK-Android/blob/fa93176fce5a81614796a53faaf64177bfe8d4a2/library/src/main/java/company/tap/gosellapi/internal/api/responses/SDKSettings.java#L33) which is null.

The field is set with the data that comes from the `/init` endpoint.
The response that I'm getting from it is:
```
{  
   "status":"success",
   "data":{  
      "merchant":{  
         "name":"*****",
         "logo":"*****"
      },
      "sdk_settings":{  
         "status_display_duration":5,
         "otp_resend_interval":60,
         "otp_resend_attempts":3
      },
      "live_mode":false,
      "livemode":false,
      "verified_application":true,
      "encryption_key":"*****",
      "device_id":null,
      "session_token":"*****"
   }
}
```

So I thing we could be having 2 issues:
1. The backend is missing the permission field
2. The sdk should check that `permissions` field is not null.

Then I reviewed ios implementation and it's checking that the permission field is not null. So I think the issue is that the Android sdk is not checking the permission field.

**Comment by Haitham001** [comment]
Dear,
      Kindly integrate with the latest version '
com.github.Tap-Payments:goSellSDK-Android:2.2.1'.
Let me know if you still face any other issues.
Regards,
*Sincerely,*
*Haitham Elsheshtawy*
*http://about.me/Haitham.Sheshtawy <http://about.me/Haitham.Sheshtawy>*
