### ISSUE TITLE
[2.2.5] Proguard is not working

### ISSUE THREAD

**Issue by matir91** [Tap-Payments/goSellSDK-Android#17]
The sdk doesn't work if Proguard is enabled, you can take a look at https://github.com/xmartlabs/goSellSDK-Android/commit/0325ee79eabeb20c09cbe86b5c084daa2c34df3d

**Comment by HaithamSheshtawy** [comment]
Maybe the reason is one of two:

If you have an older installation on your phone(with a debug key), please uninstall it first. (You can't have the same app with two different signatures on your device)

Assuming you're keeping ADT up to date.
If you're building the release version of your application using Eclipse export, it will load Proguard settings from the file specified by the proguard.config property in project.properties.

If you are using ant release, it will load the Proguard settings from the file specified by the proguard.config property in ant.properties.

That being said, are you getting any kind of errors or warnings during your build? These are especially helpful when diagnosing Proguard since it's purpose is to remove classes and methods that it doesn't think are being used by your application.

**Comment by HaithamSheshtawy** [comment]
The key to fixing the build is looking at the build output messages, understanding what the warnings are about and addressing them, usually by fixing your dependencies or adding -dontwarn rules to your ProGuard config.

**Comment by matir91** [comment]
You have problems in TAP-GLKIt android dependency, I think it's using reflection. You should define these rules in the sdk documentation, I think it's not a application issue. 

If you ran my sample application you will see a crash.
Thanks!

**Comment by matir91** [comment]
Have you defined these rules? I think this shouldn't be closed until the library defines the rules Here you can see an example of one of the [biggest library on android](https://github.com/square/okhttp/#r8--proguard)

**Comment by Haitham001** [comment]
I did, But it will be available in the next release.
Next release will expose an API to get list of saved cards for current
customer.

*Sincerely,*
*Haitham Elsheshtawy*
*http://about.me/Haitham.Sheshtawy <http://about.me/Haitham.Sheshtawy>*

**Comment by matir91** [comment]
this is not fixed, please test it. I added the solution in #21
